<div class="col-sm-12 col-xs-12">






    <style>


        .page-main-actions1 .page-actions1._fixed {
            left: 109px;
            position: fixed;
            top: 138px;
            z-index: 501;
            width: 100%;
            padding: 7px 0px 18px 0px;
        }
        .page-main-actions1:not(._hidden), .page-actions1._fixed {
            background: #f8f8f8;
           
            }



    </style>

    <div class="field required">
        <?php
        $requestStoreid = "";
        if (isset($_GET['store_id'])) {
            $requestStoreid = $_GET['store_id'];
        }

        $sellerStores = $this->getSellerData();

        if ($sellerStores === false) {
            echo "No, Store Definded!!!";
            return;
        }
        $sellerId = $this->getCustomerId();
        $storeCatalogHelper = $this->helper("Bakeway\StoreCatalog\Helper\Data");

        $catCollection = $storeCatalogHelper->getCategoriesCollection(null);

        $sellerName = "NA";
        $sellerName = $storeCatalogHelper->getSellerIdBySellerId($sellerId);
        if (isset($sellerName) && !empty($sellerName)) {
            $sellerName = $sellerName;
        }
        if (count($sellerStores) > 0) {
            ?>

            <div class="control col-sm-12 col-xs-12">
                <div class="control col-sm-9 col-xs-9">
                    <div class="control col-sm-3 col-xs-3"> 
                        <label class="label admin__field-label" for="marketplace_bakeway_partner_catalog_rule_id" data-ui-id="newsletter-fieldset-element-select-bakeway-partner-catalog-rule-id-label"><span><?php echo __("Select Store:") ?></span></label>
                    </div>
                    <div class="control col-sm-7 col-xs-7">
                        <select id="storedd_catalog" name="set" class="select admin__control-select" onchange="selectStoreSwitcher()" aria-required="true">
                            <?php foreach ($sellerStores as $sellerStore) { ?>
                                <option value="<?php echo $sellerStore['id'] ?>" <?php if ($requestStoreid == $sellerStore['id']) { ?> selected="selected" <?php } ?>  ><?php echo $sellerStore['store_headline'] . " " . $sellerStore['store_locality_area'] ?></option>
                            <?php } ?> 
    <!--<option value="s_m_store"><?php echo __("Select Multiple Store"); ?></option>-->

                        </select>

                    </div>

                    <!--<div class="control  col-sm-12 col-xs-12" id="multiple-stores" style="display:none" >
                    <br>
                        <div class="control col-sm-3 col-xs-3"> 
                        <label class="label admin__field-label" for="marketplace_bakeway_partner_catalog_rule_id" data-ui-id="newsletter-fieldset-element-select-bakeway-partner-catalog-rule-id-label"><span><?php echo __("Select Multiple Store:") ?></span></label>
                    </div>
                        <select name="multiple-stores-id" size="5" multiple id="multiple-stores-id">
                    <?php foreach ($sellerStores as $sellerStore) { ?>
                                                                            <option value="<?php echo $sellerStore['id'] ?>" <?php if ($requestStoreid == $sellerStore['id']) { ?> selected="selected" <?php } ?>  ><?php echo $sellerStore['store_headline'] . " " . $sellerStore['store_locality_area'] ?></option>
                    <?php } ?> 
                        </select>
                        <br>
                        <br>
                     </div>-->    

                </div>



                <div class="page-main-actions1">
                    <div class="page-actions1"> 
                        <div class="control col-sm-3 col-xs-3" style="float:right">
                            <button type="submit" title="Submit"  onClick="submitAction(this.id)" id="save-action" class="button submit-catalog add active-catalog-save" value="Add Row">
                                <span><span><span>Save</span></span></span>
                            </button>
                            <button type="submit" title="Submit"  onClick="document.location.reload(true)" class="button submit-catalog add active-catalog-save" value="Add Row">
                                <span><span><span>Reset</span></span></span>
                            </button>
                        </div>

                    </div>
                </div>
            </div>
        </div>

        <br/>
        <br/>

        <br/>
        <div class="clear"></div>

        <?php
        $firstStoreCatalog = current($sellerStores);

        if (!empty($requestStoreid)) {
            $productsIdArray = $storeCatalogHelper->getSellerStoreProduct($requestStoreid, $sellerId);
        } else {
            $productsIdArray = $storeCatalogHelper->getSellerStoreProduct($firstStoreCatalog['id'], $sellerId);
        }
        ?>
        <div id="store-catalog-box">

            <div class="col-sm-6" style="width: 40%;float: left;">
                <?php
                $products = $storeCatalogHelper->getSellerProducts($sellerId);
                if (count($products) > 0) {
                    ?>
                    <?php
                    $productCount = [];
                    foreach ($products as $productkey => $productvalue) {
                        if (!in_array($productkey, $productsIdArray)) {
                            $productCount[] = $productkey;
                            ?>
                            <?php
                        }
                    }
                    ?>

                    <span>
                        <h3>
                            <strong><?php echo __('Active') ?></strong>
                            (<?php echo count($productCount); ?>)
                        </h3>
                    </span>


                    <ul class="sortable-list" style="overflow-y: scroll;height: 380px;">


                        <?php
                        foreach ($products as $productkey => $productvalue) {
                            if (!in_array($productkey, $productsIdArray)) {
                                $productName = $storeCatalogHelper->getProductDetails($productkey);
                                ?>
                                <li value="<?php echo $productkey ?>" class="sortable-item product_<?php echo $productkey ?>"><?php echo $productName ?></li>

                                <?php
                            }
                        }
                        ?>
                    </ul>

                <?php } else { ?>
                    <div class="column left first">
                        <?php echo "Sorry, no Product Found!!!"; ?>
                    </div>
                <?php } ?>

            </div>

            <div class="col-sm-6 selected-products" style="width: 40%;float: left; margin-left: 5%">


                <?php
                $storeId = "";
                $storeId = $firstStoreCatalog['id'];
                if (!empty($requestStoreid)) {
                    $storeId = $requestStoreid;
                }

                $productsIdArrayofInactivePro = $storeCatalogHelper->getSellerStoreProduct($storeId, $sellerId, false, true);

                if (count($productsIdArrayofInactivePro) > 0) {
                    ?>

                    <?php ?>
                    <span><h3><strong><?php echo __('Inactive') ?> (<?php echo count($productsIdArrayofInactivePro); ?>)</strong></h3></span>


                    <ul class="sortable-list" style="overflow-y: scroll;height: 380px;">
                        <?php
                        foreach ($productsIdArrayofInactivePro as $productData) {
                            $productName = $storeCatalogHelper->getProductDetails($productData['product_id']);
                            ?>
                            <li value="<?php echo $productData['product_id'] ?>" class="sortable-item product_<?php echo $productData['product_id'] ?>"><?php echo $productName ?></li>
                            <?php
                        }
                        ?>
                    </ul>

                <?php } else { ?>
                    <div class="column left first sortable-list">
                        <?php echo "Sorry, no Product Found!!!"; ?>
                    </div>
                <?php } ?>
            </div>

            <input type="hidden" id="storeUrl" name="storeUrl" value="<?php
            echo $this->getUrl('customer/index/edit/', array('id' => $sellerId, '_current' => true, 'mode' => 'storecatalog_save_target'));
            ?>" />
        </div>
    </div>

    <style type="text/css">
        .sortable-list,.sortable-list1  {
            background: aliceblue;
            list-style: none;
            margin: 0;
            min-height: 60px;
            padding: 10px;
        }
        .sortable-item, .sortable-item1 {
            background-color: #FFF;
            border: 1px solid #000;
            cursor: move;
            display: block;
            font-weight: bold;
            margin-bottom: 5px;
            padding: 1px 1px 1px 8px;
            text-align: left;
        }
        #containment {
            background-color: #FFA;
            height: 230px;
        }

        .placeholder {
            background-color: #BFB;
            border: 1px dashed #666;
            height: 58px;
            margin-bottom: 5px;
        }
        .account.page-layout-2columns-left .column.main{width:74.7%}
        #store-catalog-box .submit-catalog{ background-color: #eb5202 !important; margin-bottom: 10px;}
        #store-catalog-box .submit-catalog span{ color: #fff; text-transform: uppercase; font-weight: bold}
        .sortable-list li.selected, .sortable-list1 li.selected  {background-color:#eb5202;color:#fff};

    </style>
    <script type="text/javascript">
        var seller_id = "<?php echo $sellerId ?>";
        var seller_name = "<?php echo $sellerName; ?>";
        var locality_id = document.getElementById("storedd_catalog").value;
        var catalouge_select_Url = "<?php echo $this->getUrl('storecatalog/index/select', ['_secure' => true]); ?>";
        var catalouge_submit_Url = "<?php echo $this->getUrl('storecatalog/index/submit', ['_secure' => true]); ?>";
        var controller_url = document.getElementById("storeUrl").value;
        document.getElementById("save-action").disabled = true;
        require(['jquery', 'jquery/ui'], function (jQuery)
        {

            jQuery("#store-catalog-box .sortable-list,#store-catalog-box .sortable-list1").on('click', 'li', function (e) {
                if (e.ctrlKey || e.metaKey) {
                    jQuery(this).toggleClass("selected");
                } else {
                    jQuery(this).addClass("selected").siblings().removeClass('selected');
                }
            }).sortable({
                connectWith: "#store-catalog-box .sortable-list,#store-catalog-box .sortable-list1", placeholder: 'placeholder',
                delay: 150, //Needed to prevent accidental drag when trying to select
                revert: 0,
                helper: function (e, item) {
                    //Basically, if you grab an unhighlighted item to drag, it will deselect (unhighlight) everything else
                    if (!item.hasClass('selected')) {
                        item.addClass('selected').siblings().removeClass('selected');
                    }
                    var elements = item.parent().children('.selected').clone();
                    item.data('multidrag', elements).siblings('.selected').remove();
                    document.getElementById("save-action").disabled = false;
                    var helper = jQuery('<li/>');
                    return helper.append(elements);
                },
                stop: function (e, ui) {
                    //Now we access those items that we stored in `item`s data!
                    var elements = ui.item.data('multidrag');
                    ui.item.after(elements).remove();
                }

            });
            jQuery("#catalog-save,#catalog-update").attr("disabled", "disabled");
            jQuery("#storedd_catalog").change(function () {
                var locality_id = document.getElementById("storedd_catalog").value;

                /**
                 if(locality_id == "s_m_store"){
                 document.getElementById("multiple-stores").style.display = "block";
                 document.getElementById("save-action").disabled = false;
                 var multistores = [];
                 jQuery.each(jQuery("#multiple-stores-id option:selected"), function(){            
                 multistores.push(jQuery(this).val());
                 console.log(multistores);
                 });
                 }
                 **/

                jQuery.ajax(catalouge_select_Url, {
                    method: 'post',
                    dataType: "json",
                    data: {
                        locality_id: locality_id, seller_id: seller_id
                    },
                    showLoader: true,
                    success: function (data) {
                        if (data.seller_id != null && data.store_id != null) {
                            var storeUrl = jQuery('#storeUrl').val();
                            var mainUri = storeUrl.split('?')[0];
                            window.location.href = (mainUri + "?store_id=" + data.store_id);
                        }

                    }
                });
            })

            jQuery(window).scroll(function () {
                if (jQuery(window).scrollTop() >= 200) {
                    jQuery('.page-actions1').addClass('_fixed');
                    jQuery('.page-actions1 div').addClass('visible-title');
                } else {
                    jQuery('.page-actions1').removeClass('_fixed');
                    jQuery('.page-actions1 div').removeClass('visible-title');
                }
            });


        });
        /**
         * getAllSelectedProducts method
         */
        function submitAction(value) {

        /**var locality_id = document.getElementById("storedd_catalog").value;
             
         if (locality_id == "s_m_store") {
         document.getElementById("multiple-stores").style.display = "block";
         document.getElementById("save-action").disabled = false;
         var multistores = [];
         jQuery.each(jQuery("#multiple-stores-id option:selected"), function () {
         multistores.push(jQuery(this).val());
         console.log(multistores);
         });
         }
         **/
        const listItems = document.querySelectorAll('.selected-products li');
                productsItemsarray = "";
                var action_value = value;
                for (let i = 0; i < listItems.length;
                        i++
                        ) {
        liob = listItems[i];
                productsItemsarray += listItems[i].value + ",";
        }

        const listItemsforCats = document.querySelectorAll('.selected-products1 li');
                categoriesArray = "";
                for (let i = 0; i < listItemsforCats.length;
                        i++
                        ) {
        liob = listItemsforCats[i];
                categoriesArray += listItemsforCats[i].value + ",";
        }

        const listItemsforActiveCats = document.querySelectorAll('.active-cats .sortable-list1 li');
                activeCategoriesArray = "";
                for (let i = 0; i < listItemsforActiveCats.length;
                        i++
                        ) {
        liob = listItemsforActiveCats[i];
                activeCategoriesArray += listItemsforActiveCats[i].value + ",";
        }



        var actionEvent = value;
                if (actionEvent == 1) {
        actionEvent = 1;
        }
        var productsIds = productsItemsarray;
                var categoryIds = categoriesArray;
                var activeCatsId = activeCategoriesArray;
                require(['jquery', 'jquery/ui'], function (jQuery) {

                jQuery.ajax({
                type: "POST",
                        dataType: "json",
                        url: catalouge_submit_Url,
                        data: {actionEvent: actionEvent, seller_id: seller_id, seller_name: seller_name, productsId: productsIds, locality_id: locality_id, categoryIds: categoryIds,
                                activeCatsId : activeCatsId},
                        showLoader: true,
                        success: function (data) {
                        var resmsg = data.success;
                                if (resmsg === true) {
                        document.location.reload(true);
                                var storeUrl = jQuery('#storeUrl').val();
                                var mainUri = storeUrl.split('?')[0];
                                window.location.href = (mainUri + "?store_id=" + data.store_id);
                        } else if (resmsg === false) {
                        window.location.href = (mainUri + "?store_id=" + data.store_id);
                        }

                        }
                });
                        return false;
                });
        }
    </script> 
    <br>
    <br>
    <br>
    <?php if (!empty($catCollection)) { ?>

        <?php
        if (!empty($requestStoreid)) {
            $requestStoreid = $requestStoreid;
        } else {
            $requestStoreid = $firstStoreCatalog['id'];
        }
        $oldCatArray = $activeCatArray = [];

        $catActiveCollection = $storeCatalogHelper->getSellerStoreActiveCategories($requestStoreid, $sellerId);
        ?>

        <div id="store-catalog-box">

            <div class="col-sm-6 active-cats" style="width: 40%;float: left; margin-top: 60px;">
                <span>
                    <h3>
                        <strong><?php echo __('Active Categories') ?></strong>
                        (<?php echo count($catActiveCollection); ?>)
                    </h3>
                </span>


                <?php if (count($catActiveCollection) > 0) {
                    ?>
                    <ul class="sortable-list1" style="overflow-y: scroll;height: 380px;">

                        <?php
                        foreach ($catActiveCollection as $cat) {

                            $activeCatArray[] = $cat['id'];
                            ?>
                            <li value="<?php echo $cat['id'] ?>" class="sortable-item product_<?php echo $cat['name'] ?>">
                                <span style="padding-left:<?php echo $cat['level'] * 3 ?>%">&nbsp;</span>    <?php echo $cat['name'] ?>
                            </li>
                            <?php
                        }
                        ?>                       
                    </ul>

                <?php } else { ?>
                    <div class="column left first sortable-list1">
                        <?php echo "Sorry, no Categories Found!!!"; ?>
                    </div>
                <?php } ?>
            </div>
            <?php
            $inactivecatCollection = $storeCatalogHelper->getCategoriesCollection($oldCatArray);
            ?>
            <div class="col-sm-6 selected-products1" style="margin-top: 60px;width: 40%;float: left; margin-left: 5%">
                <span>
                    <h3>
                        <strong><?php echo __('Inactive Categories') ?></strong>

                        (<?php
                        if (count($catCollection) > 0) {
                            echo count($catCollection) - count($catActiveCollection);
                        } else {
                            echo 0;
                        }
                        ?>)
                    </h3>
                </span>
                <?php if (count($catCollection) > 0) { ?>
                    <ul class="sortable-list1" style="overflow-y: scroll;height: 380px;">
                        <?php
                        foreach ($catCollection as $cat) {
                            if (!in_array($cat['id'], $activeCatArray)) {
                                ?>
                                <li value="<?php echo $cat['id'] ?>" class="sortable-item product_<?php echo $cat['name'] ?>">
                                    <span style="padding-left:<?php echo $cat['level'] * 3 ?>%">&nbsp;</span>    <?php echo $cat['name'] ?>
                                </li>
                                <?php
                            }
                        }
                        ?> 
                    </ul>
                <?php } else { ?>
                    <div class="column left first sortable-list1">
                        <?php echo "Sorry, no Categories Found!!!"; ?>
                    </div>
                <?php } ?>    
            </div>
        </div>

    <?php }
    ?>


<?php } else { ?>
    <?php echo "Sorry, No Store Found!!!"; ?>
<?php } ?>


