<?php
/**
 * Copyright © 2015 Smj. All rights reserved.
 * See COPYING.txt for license details.
 *
 *
 * Smj_Zohocrm extension
 * NOTICE OF LICENSE
 *
 * @category  Smj
 * @package   Smj_Zohocrm
 * @author Mukund
 */
?>
<script>
    require([
        "Smj_Zohocrm/js/fields",
        "domReady!"
    ], function (Fields) {
        var fields = new Fields({url : '<?php echo $this->getUpdateUrl()?>'});
    });
</script>
<script>
    require(["jquery"], function(jQuery){
        jQuery("#updateallfields").click(function(){
            var url = '<?php echo $this->getUpdateAllFields(); ?>';
            jQuery.ajax({
                type: "POST",
                url: url,
                data: {
                    form_key: FORM_KEY
                },
                showLoader: true,
                success: function(){
                    alert('Update success');
                }
            });
        });
    });
</script>
