<?php
/**
 * Copyright © 2015 Smj. All rights reserved.
 * See COPYING.txt for license details.
 *
 *
 * Smj_Zohocrm extension
 * NOTICE OF LICENSE
 *
 * @category  Smj
 * @package   Smj_Zohocrm
 * @author CanhND
 */
?>
<?php
    /** @var $block \Smj\Zohocrm\Block\System\Config\Form\Button\Button */
?>
<div class="actions button-container">
    <a href="<?php /* @escapeNotVerified */ echo $block->escapeUrl($block->getButtonUrl()) ?>">
        <button  class="button action-configure"
                 type="button"
                 data-role="<?php /* @escapeNotVerified */ echo $block->getHtmlId() ?>"
                 id="<?php /* @escapeNotVerified */ echo $block->getHtmlId() ?>" disabled="disabled">
            <span><?php /* @escapeNotVerified */ echo $block->escapeHtml($block->getButtonLabel()) ?></span>
        </button>
    </a>
</div>