<?php $themeHelper = $this->helper('MGS\Mpanel\Helper\Data'); ?>
<?php if($themeHelper->getStoreConfig('mpanel/share_config/enabel_share')): ?>
	<?php echo $themeHelper->getStoreConfig('mpanel/share_config/html_share'); ?>
<?php endif ?>

<!-- tab block -->
<?php 
      echo $this->getLayout()->createBlock('Magento\Framework\View\Element\Template')->setTemplate('MGS_Protabs::product/view/details.phtml')->toHtml();
?>