<?php $images = $this->getImages(); ?>
<?php $fullwidth = $this->getFullscreen(); ?>
<?php $fullheight = $this->getFullheight(); ?>
<?php $prlSlider = $this->getParallax(); ?>
<?php $offset = $this->getOffset(); ?>
<?php if($prlSlider){ $fullheight = true; } ?>

<?php if(count($images)>0): ?>
	<?php $links = $this->getLinks() ?>
	<?php $blockId = rand() . time(); ?>
	<?php $animated = $this->getAnimateSlider(); ?>
		<div id="page-header-sliders" class="page-header-sliders <?php if($fullheight): ?> fullscreen-slider<?php endif ?>">
            <?php if($fullwidth && !$prlSlider): ?><div class="row"><?php endif ?>
            <div id="mgs-slider-<?php echo $blockId ?>" class="slider_mgs_carousel owl-carousel">
                <?php foreach($images as $key=>$image): ?>
                    <?php if($fullheight): ?>
                        <div class="item fullscreen" <?php if(isset($links[$key]) && ($links[$key]!='')): ?>onclick="setLocation('<?php echo $links[$key] ?>')"<?php endif ?> style="background-image:url('<?php echo $image ?>')">
                        </div>
                    <?php else: ?>
                        <div class="item">
                            <a href="<?php if(isset($links[$key]) && ($links[$key]!='')): ?><?php echo $links[$key] ?><?php else: ?>javascript:void(0)<?php endif ?>">
                                <img src="<?php echo $image ?>" alt=""/>
                            </a>
                        </div>
                    <?php endif ?>
                <?php endforeach ?>
            </div>
            <?php if($fullwidth): ?></div><?php endif ?>
		</div>
	<script type="text/javascript">
		require([
			'jquery',
			'mgs/owlcarousel'
		], function(jQuery){
			(function($) {
				<?php if($fullheight): ?>
                    var sliderHeight = $(window).height();
                    var offset = 0;
                    <?php if($offset): ?>
                        var offset = $('<?php echo $offset ?>').height();
                    <?php endif ?>
                    
                    $(".fullscreen-slider").height(sliderHeight - offset);
					$(window).resize(function() {
						$(".fullscreen-slider").height($(window).height() - offset);
					});
				<?php endif ?>
                <?php if($prlSlider): ?>
                    var hdH = $("header").height();
                    $("#page-header-sliders").detach().insertAfter('header');
                    $('#page-header-sliders').css('top', hdH);
                    $('main').css('margin-top', $("#page-header-sliders").height());
                    
                    $(window).resize(function() {
                        $('main').css('margin-top', $("#page-header-sliders").height());
                    });
					$(window).scroll(function() {
                        var hdH = $("header").height();
                        var scrollTop = $(this).scrollTop(),
                          height = $(window).height(),
                          offset = height,
                          calc = (height - scrollTop) / height;
                          
                        $("#page-header-sliders .slider_mgs_carousel").css({ 'opacity': calc });
                        
                        if(scrollTop > height){
                            $('.cms-index-index footer').addClass('active');
                        }else {
                            $('.cms-index-index footer').removeClass('active');
                        }
                        
                        if($('body').hasClass('boxed-full')){
                            var height_scroll = 30;
                        }else{
                            var height_scroll = 1;
                        }
                        
                        if($(this).scrollTop() > height_scroll){
							$('#page-header-sliders').css('top', 80);
						}
                        
						if($(this).scrollTop() < height_scroll){
							$('#page-header-sliders').css('top', hdH);
						}
					});
                <?php endif ?>
                
				$("#mgs-slider-<?php echo $blockId ?>").owlCarousel({
					items: 1,
                    rtl: RTL,
					loop: <?php echo $this->getLoop(); ?>,
					nav: <?php echo $this->getControlNav(); ?>,
					dots: <?php echo $this->getControlDots(); ?>,
					autoplayTimeout: <?php echo $this->getAutoSpeed(); ?>,
					autoplay: <?php echo $this->getAutoPlay(); ?>,
					autoplayHoverPause: <?php echo $this->getStopAuto() ? 'true' : 'false'; ?>,
					animateOut: '<?php echo $animated['out'] ?>',
					animateIn: '<?php echo $animated['in'] ?>',
					navText: ["<i class='pe-7s-angle-left'></i>","<i class='pe-7s-angle-right'></i>"],
                    responsive:{
                        0:{
                            nav: false,
                            dots: true
                        },
                        992:{
                            nav: <?php echo $this->getControlNav(); ?>,
                            dots: <?php echo $this->getControlDots(); ?>
                        }
                    }
				});
			})(jQuery);
		});
	</script>
<?php else: ?>
	<div role="alert" class="alert alert-warning"><?php echo __('There are no sliders matching the selection.') ?></div>
<?php endif ?>