<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
$helper =  \Magento\Framework\App\ObjectManager::getInstance()->get('MGS\Mpanel\Helper\Data');
?>
<script>
	var BASE_URL = WEB_URL = '<?= $block->escapeUrl($block->getBaseUrl()) ?>';
	var RTL = false;
    var CATALOG_CHECK = 0;
    var fullAction = '<?php echo $helper->getFullActionName(); ?>';
    if(fullAction === 'catalog_category_view') {
        CATALOG_CHECK = 1;
    } else if (fullAction === 'catalog_product_view' || fullAction === 'mgs_quickview_catalog_product_view') {
        CATALOG_CHECK = 2;
    }

    var require = {
        "baseUrl": "<?= /* @escapeNotVerified */ $block->getViewFileUrl('/') ?>"
    };
</script>
